const zach = [
  {
    id : 1,
    disciplina: "Технологии Web-разработки",
    hours: "108",
    itog: "Отлично",
    date: "2022-01-19",
    control: "Экзамен",
    teacher: "Пепелышев Д.И.",
  },
  {
    id : 2,
    disciplina: "Математика",
    hours: "200",
    itog: "Удовлетворительно",
    date: "2022-01-10",
    control: "Экзамен",
    teacher: "Демина А.Н.",
  },
  {
    id : 3,
    disciplina: "Физика",
    hours: "280",
    itog: "Удовлетворительно",
    date: "2022-01-13",
    control: "Экзамен",
    teacher: "Демин Е.Д.",
  },
  {
    id : 4,
    disciplina: "История",
    hours: "85",
    itog: "Отлично",
    date: "2022-01-16",
    control: "Зачет",
    teacher: "Докучаев А.О.",
  },
  {
    id : 5,
    disciplina: "Проектирование",
    hours: "97",
    itog: "Хорошо",
    date: "2022-01-22",
    control: "Зачет",
    teacher: "Лапина Е.К.",
  },
  {
    id : 6,
    disciplina: "Пэк",
    hours: "66",
    itog: "Отлично",
    date: "2022-01-24",
    control: "Зачет",
    teacher: "Паньшин А.А.",
  },
];
export default zach;
